### PR TITLE
Introduce NameSufiix 

### PR DESCRIPTION
**Pull request by potsbo**
## Why

In the discussion https://github.com/wantedly/deployment-duplicator/pull/1/files/a03aac79fe950e3bfe3af9efad470e407ab46272#r430971153, we decided not to have `NameSuffix`, instead we use `.metadata.name` for the purpose.
But after trying this controller in my environment I faced a minor problem.

When trying to copy deployment `some-very-long-deployment-name`, it's kind of reasonable to name `DeploymentCopy` `some-very-long-deployment-name` to avoid conflict in a namespace, which results in creating a deployment named `some-very-long-deployment-name-some-very-long-deployment-name`.
This is troublesome.

## What

Added an option to set suffix.
As @munisystem mentioned, k8s controllers usually don't ask suffix to set, but since `deployment` is an important resource and people expect they have meaningful names on it.
I think the option is useful.

### CODE REVIEW

**Comment by potsbo** [comment]
@munisystem any opinion?
Having random string as suffix is another option.

**Comment by munisystem** [comment]
Do you need the original deployment name in the copy's? If that, I think good this change.

**Comment by potsbo** [comment]
> Do you need the original deployment name in the copy's? If that, I think good this change.

Technically, it's not necessary, but I think it's very nice for usability.

**Comment by potsbo** [comment]
Since you don't have a strong objection, I would like your review to merge this to master.
@munisystem

**Pull request merged**
